// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJsERdBu-LHvooOH5DQ1khs7SXou7AH9w',
    appId: '1:657126844293:web:1569a4b552601911e486ec',
    messagingSenderId: '657126844293',
    projectId: 'e-book-store-c10cf',
    authDomain: 'e-book-store-c10cf.firebaseapp.com',
    storageBucket: 'e-book-store-c10cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEoFUANu8cJ7ORc8J-SqUBrGXxz_oN3B8',
    appId: '1:657126844293:android:ee3ae97ee7b63dcde486ec',
    messagingSenderId: '657126844293',
    projectId: 'e-book-store-c10cf',
    storageBucket: 'e-book-store-c10cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDil2tgdyWu4taoX3LHF2WPg31jHqmBon8',
    appId: '1:657126844293:ios:d47b5757bb61db80e486ec',
    messagingSenderId: '657126844293',
    projectId: 'e-book-store-c10cf',
    storageBucket: 'e-book-store-c10cf.appspot.com',
    iosBundleId: 'com.example.ebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDil2tgdyWu4taoX3LHF2WPg31jHqmBon8',
    appId: '1:657126844293:ios:d47b5757bb61db80e486ec',
    messagingSenderId: '657126844293',
    projectId: 'e-book-store-c10cf',
    storageBucket: 'e-book-store-c10cf.appspot.com',
    iosBundleId: 'com.example.ebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJsERdBu-LHvooOH5DQ1khs7SXou7AH9w',
    appId: '1:657126844293:web:440e7a5644f5eea2e486ec',
    messagingSenderId: '657126844293',
    projectId: 'e-book-store-c10cf',
    authDomain: 'e-book-store-c10cf.firebaseapp.com',
    storageBucket: 'e-book-store-c10cf.appspot.com',
  );
}
